default:
  base_dir: /home/davidkarapetyan/Documents/workspace/Adirondack/TPO2-Rudin
  python_prog: /home/davidkarapetyan/anaconda3/bin/python
  data_sources: /data
  log_dir: /var/log
  buildings:
    - 345_Park
  # run mode
  debug: True

  345_Park:
      floor_quadrants:
        -
          - 24
          - NW
        -
          - 24
          - NE

      # electric
      electric_meter_count: 6
      # electric -> benchmark
      collection_name_out: analytics


building_dbs:
  mongo_cred:
      host: 52.90.177.221 #datascience.local #52.91.89.104
      port: 27017
      source: admin
      username: Analytics
      password: L3x1^gt0n
  wund_cred:
      wund_url: http://api.wunderground.com/api/bab4ba5bcbc2dbec/
    # wund_url: http://api.wunderground.com/api/08d25f404214f50b/
      city: New_York
      state: NY
  weather_forecast_loc:
      db_name: weather
      collection_name: forecast
  weather_history_loc:
      db_name: weather
      collection_name: history
  building_ts_loc:
      db_name: skynet
      collection_name: devicetimeseries
  results:
      db_name_out: skynet
      collection_name_out: analytics



#cov: [conds, hum, rain, snow, temp]
weather:
  cov: [wetbulb]
  seasons: {spring: [3, 6], summer: [6, 9], fall: [9, 12], winter: [12, 3]}
  # cov choice is constrained by column entries in wund forecast which is
  # sparser than those in history data from wund. For example no
  # tornado or thunder seen so far in forecasts
  conds_mapping:
    Clear: 0
    Cloudy: 16
    Fog: 9
    Haze: 3
    Heavy Rain: 8
    Heavy Snow: 14
    Light Freezing Rain: 15
    Light Rain: 6
    Light Snow: 11
    Mist: 13
    Mostly Cloudy: 4
    Overcast: 5
    Partly Cloudy: 2
    Rain: 7
    Scattered Clouds: 1
    Showers: 7 #same as rain, since historical data doesn't have 'showers'
    Snow: 12
    Unknown: 10
  wdire_mapping:
    ENE: 6
    ESE: 12
    East: 15
    NE: 5
    NNE: 3
    NNW: 4
    NW: 16
    North: 1
    SE: 10
    SSE: 11
    SSW: 13
    SW: 8
    South: 14
    Variable: 0
    WNW: 9
    WSW: 7
    West: 2

sampling:
  granularity: 15min
  forecast_length: 24
  nary_thresh: 100
# upper bound for number of unique points before time
# series is classed as n-ary instead of continuous

svm:
  params:
  cache_size: 30000
  max_iter: -1
  probability: False
  random_state: 1
  shrinking: True
  tol: 0.001
  verbose: False

param_search:
grid:
  C:
    start: 1 # arr_start = base ** start
    stop : 5 # arr_stop = base ** stop
    base : 10 #logarithmic base
    num : 50 #number of samples to generate
  gamma:
    start: -5
    stop: 1
    base: 10
    num: 50
  kernel:
    - rbf
cv: 3 #number of Kfold cross validation folds
n_jobs: -1
threshold: 0.003


arima:
  order:
    - 1
    - 1
    - 0

parallel:
processors: -1

