david :
  default:
    base_dir: /home/davidkarapetyan/Documents/workspace/Adirondack/TPO2-Rudin
    python_prog: /home/davidkarapetyan/anaconda3/bin/python
    data_sources: /data
    log_dir: /var/log

  weather:
    h5file: /data/weather.h5
    # wund_url: http://api.wunderground.com/api/08d25f404214f50b/
    wund_url: http://api.wunderground.com/api/bab4ba5bcbc2dbec/
    #cov: [conds, hum, rain, snow, temp]
    cov: [hum, temp]
    seasons: {spring: [3, 6], summer: [6, 9], fall: [9, 12], winter: [12, 3]}
    # cov choice is constrained by column entries in wund forecast which is
    # sparser than those in history data from wund. For example no
    # tornado or thunder seen so far in forecasts
    conds_mapping:
      Clear: 0
      Cloudy: 16
      Fog: 9
      Haze: 3
      Heavy Rain: 8
      Heavy Snow: 14
      Light Freezing Rain: 15
      Light Rain: 6
      Light Snow: 11
      Mist: 13
      Mostly Cloudy: 4
      Overcast: 5
      Partly Cloudy: 2
      Rain: 7
      Scattered Clouds: 1
      Showers: 7 #same as rain, since historical data doesn't have 'showers'
      Snow: 12
      Unknown: 10
    wdire_mapping:
      ENE: 6
      ESE: 12
      East: 15
      NE: 5
      NNE: 3
      NNW: 4
      NW: 16
      North: 1
      SE: 10
      SSE: 11
      SSW: 13
      SW: 8
      South: 14
      Variable: 0
      WNW: 9
      WSW: 7
      West: 2
    history_orig: history_orig
    history: history
    forecast_orig: forecast_orig
    forecast: forecast
    city: New_York
    state: NY
    cap: 90000000

  sampling:
    granularity: 15min
    forecast_length: 24
    nary_thresh: 100
    # upper bound for number of unique points before time
    # series is classed as n-ary instead of continuous

  svm:
    params:
      gamma: 3
      C: 1
      cache_size: 10000
      kernel: rbf
      max_iter: -1
      probability: False
      random_state: 1
      shrinking: True
      tol: 0.001
      verbose: False

    cross_val:
      param_grid:
          C:
            - 50
            - 100
            - 200
            - 300
            - 400
            - 500
            - 1000
            - 5000
            - 10000

          gamma:
            - 0.0005
            - 0.001
            - 0.00125
            - 0.0015
            - 0.001625
            - 0.00175
            - 0.002
            - 0.00225
            - 0.0025

          kernel:
            - rbf
      n_jobs: -1
      threshold: 0.003


  sarima:
    order: [1, 1, 0]
    seasonal_order: [1, 1, 3]
    enforce_stationarity: False

  parallel:
    processors: 24

  database:
    db_server_input: 52.91.89.104
    db_user_input: None
    db_password_input: None
    db_name_input: skynet
    collection_name_input: devicetimeseries
    floor_quadrants: [[24, NW], [24, NE]]



ashish:

  default:
    base_dir: /home/ashishgagneja/Adirondack/analytics/TPO2-Rudin
    python_prog: /home/davidkarapetyan/anaconda3/bin/python
    data_sources: /data
    log_dir: /var/log
    # run mode
    debug: True

#     list of building ids. There should be a key corresponding to each
#     name on this list elsewhere in this configuration spec.
    buildings: [345_Park, ]


  weather:
    h5file: /data/weather.h5
    # wund_url: http://api.wunderground.com/api/08d25f404214f50b/
    wund_url: http://api.wunderground.com/api/bab4ba5bcbc2dbec/
    #cov: [conds, hum, rain, snow, temp]
    cov: [hum, temp]
    seasons: {spring: [3, 6], summer: [6, 9], fall: [9, 12], winter: [12, 3]}
    # cov choice is constrained by column entries in wund forecast which is
    # sparser than those in history data from wund. For example no
    # tornado or thunder seen so far in forecasts
    conds_mapping:
      Clear: 0
      Cloudy: 16
      Fog: 9
      Haze: 3
      Heavy Rain: 8
      Heavy Snow: 14
      Light Freezing Rain: 15
      Light Rain: 6
      Light Snow: 11
      Mist: 13
      Mostly Cloudy: 4
      Overcast: 5
      Partly Cloudy: 2
      Rain: 7
      Scattered Clouds: 1
      Showers: 7 #same as showers, since historical data doesn't have 'showers'
      Snow: 12
      Unknown: 10
    wdire_mapping:
      ENE: 6
      ESE: 12
      East: 15
      NE: 5
      NNE: 3
      NNW: 4
      NW: 16
      North: 1
      SE: 10
      SSE: 11
      SSW: 13
      SW: 8
      South: 14
      Variable: 0
      WNW: 9
      WSW: 7
      West: 2
    history_orig: history_orig
    history: history
    forecast_orig: forecast_orig
    forecast: forecast
    city: New_York
    state: NY
    cap: 90000000


  sampling:
    granularity: 15
    forecast_length: 24
    nary_thresh: 100
    # upper bound for number of unique points before time
    # series is classed as n-ary instead of continuous
    max_gap: 2
    # largest allowed gap in data in hours


  svm:
    gamma: 1
    C: 1
    cache_size: 10000
    kernel: rbf
    max_iter: -1
    probability: False
    random_state: None
    shrinking: True
    tol: 0.001
    verbose: False


  sarima:
    order: [1, 1, 0]
    seasonal_order: [1, 1, 3]
    enforce_stationarity: False


  345_Park:
    steam_data: /home/davidkarapetyan/data_analysis/data/park345.h5
    steam_data_group: oa_temp

    # database for input data
    db_server_input: 52.91.89.104
    db_user_input: None
    db_password_input: None
    db_name_input: skynet
    collection_name_input: devicetimeseries


    floor_quadrants: [[24, NW], [24, NE]]

    # electric
    electric_meter_count: 6


master: None